# Site settings
title: nonstandardard deviations
baseurl: "/nonstandard_deviations"
url: "http://lreding.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics:
disqus_shortname: 
